name: GH-Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Install Dependencies
        run: flutter pub get
        working-directory: ./visualizer
      - name: Build Web
        run: flutter build web --release # --source-maps
        working-directory: ./visualizer
      - name: Deploy
        run: |
          cd visualizer/build/web
          git init
          git config user.name "bdlukaa"
          git config user.email "brunodlukaa@github.com"
          git remote add secure-origin https://username:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git checkout -b gh-pages
          git add .
          git commit -m "Deployed Github Pages"
          git push --force secure-origin gh-pages